- hosts: kube_server
  become: true
  remote_user: ubuntu
  
  vars_files:
    - ansible-vars.yml
    
  tasks:

  - name: Ensure containerd is installed.
    package:
      name: containerd.io
      state: present

  - name: Ensure containerd is started and enabled at boot.
    service:
      name: containerd
      state: started
      enabled: true

  - name: Ensure containerd config directory exists.
    file:
      path: /etc/containerd
      state: directory
    register: containerd_dir
 
  - name: Configure containerd so that it starts using systemd as cgroup
    ansible.builtin.shell: "{{ item }}"
    with_items:
      - containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
      - sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted
    
  - name: Initialize Kubernetes cluster
    command: "kubeadm init --pod-network-cidr {{ pod_cidr }}"
    args:
      creates: /etc/kubernetes/admin.conf  # skip this task if the file already exists
    register: kube_init
    
  - name: Show kube init info
    debug:
      var: kube_init
      
  - name: Create .kube directory in user home
    file:
      path: "{{ home_dir }}/.kube"
      state: directory
      owner: 1000
      group: 1000

  - name: Configure .kube/config files in user home
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ home_dir }}/.kube/config"
      remote_src: yes
      owner: 1000
      group: 1000
      
  - name: Restart kubelet for config changes
    service:
      name: kubelet
      state: restarted
      
  - name: Get Calico networking
    get_url:
      url: https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
      dest: "{{ home_dir }}/calico.yaml"
      
  - name: Apply Calico networking
    become: no
    command: kubectl apply -f "{{ home_dir }}/calico.yaml"
    
  - name: Get Dashboard
    get_url:
      url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml
      dest: "{{ home_dir }}/dashboard.yaml"
    
  - name: Apply Dashboard
    become: no
    command: kubectl apply -f "{{ home_dir }}/dashboard.yaml"
